### ISSUE TITLE
Do a redirect instead of returning the long url

### ISSUE THREAD

**Issue by manuelolmos** [manuelolmos/shortenurl#9]

**Comment by unbalancedparentheses** [comment]
Check:
https://en.wikipedia.org/wiki/HTTP_301
https://developer.mozilla.org/es/docs/Web/HTTP/Redirections

You need to answer a code 301 with the header location set.

Also check: https://ninenines.eu/docs/en/cowboy/2.2/guide/resp/
```
Req = cowboy_req:reply(301, #{
    <<"location">> => <<"https://ninenines.eu">>
}, Req0).```

**Comment by manuelolmos** [comment]
Perfect, Thanks!

**Comment by manuelolmos** [comment]
Fixed on commit https://github.com/manuelolmos/shortenurl/commit/013b94d92b26faf448465bde1aad00c239bbeb7e
